### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by simsimiSION** [CETC-TFAI/MaCA#12]
你好，我在运行程序时回出现这样的错误，，请问您这边知道如何处理吗

XXX lineno: 41, opcode: 160
Traceback (most recent call last):
  File "/home/simsimi/MaCA/fight.py", line 77, in <module>
    random_pos=args.random_pos, log=log_flag)
  File "/home/simsimi/MaCA/environment/interface.py", line 44, in __init__
    self.map = Map(map_path)
  File "<frozen environment.world.load_map>", line 41, in __init__
SystemError: unknown opcode

**Comment by fengmi1997** [comment]
请问解决了吗，我下载新版本程序也遇到相同问题，以前版本还是正常的？

**Comment by leonfg** [comment]
目前版本有问题，请暂时使用13号的版本尝试一下，还有问题再联系解决。

**Comment by leonfg** [comment]
> 
> 
> 请问解决了吗，我下载新版本程序也遇到相同问题，以前版本还是正常的？

**Comment by leonfg** [comment]
已更新，试一下行不行
