### ISSUE TITLE
可以自己建地图吗？

### ISSUE THREAD

**Issue by Jiang1206** [CETC-TFAI/MaCA#15]
不知道是什么原因，windows 10 下不能完全看到整张地图，因此我想在一个更小的地图上进行训练。但是新建了新的地图图片以及.map文件，并在main里修改了map-path，提示找不到.map文件，我想是不是因为无法对environment里的loadmap进行修改造成的错误。
所以我想知道是否有可能重建地图，或者在win10上看到地图全部？
第二就是除了核心模型外，是不是科技将地图以及其他可扩展的功能开放?让我们可以根据需要自己修改，我认为这是一个比较好的开源平台，如果只是局限在比赛的内容上就有些局限了。还是期待您可以开源一个类似的完全开放的平台。

**Comment by leonfg** [comment]
感谢使用本平台！
自己建地图没问题，环境也并没有对加载哪个地图进行限制，我们也经常自己随便改地图用。只要是使用正确的方式配置就可以加载：
1. .map地图文件放置在map文件夹中，如map/aaa.map
2.如果使用fight_mp:
`python fight_mp.py --map=aaa`
开源的问题其实最初就是向着这个方向走的，只是各种原因并不能顺着开发人员的想法发展，只能后面继续努力争取了。

**Comment by Jiang1206** [comment]
非常感谢您的回复，其实昨天发完问题已经发现错误的原因了，我自己路径写错了。期待进一步的开源！

**Comment by Jiang1206** [comment]
我有个问题，更改地图后对dqn.py要进行修改吗？我只修改了main.py的地图路径以及单元数量，但是出现了如下的错误：``C:\Anaconda3\envs\py36_MaCA\python.exe C:/Users/25796/MaCA/train/simple/5v5.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
GPU Available!!
Traceback (most recent call last):
  File "C:/Users/25796/MaCA/train/simple/5v5.py", line 74, in <module>
    tmp_action = fighter_model.choose_action(tmp_img_obs, tmp_info_obs)
  File "C:\Users\25796\MaCA\train\simple\dqn.py", line 127, in choose_action
    actions_value = self.eval_net(img_obs, info_obs)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\25796\MaCA\train\simple\dqn.py", line 51, in forward
    feature = self.feature_fc(combined)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\modules\linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Anaconda3\envs\py36_MaCA\lib\site-packages\torch\nn\functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

Process finished with exit code “
我尝试debug解决，但是发现到断点不能停下，网上的方法也并不适用，不知您那里有这样的情况吗？

**Comment by leonfg** [comment]
需要，例子里应该是指定了单位数量

**Comment by Jiang1206** [comment]
但是dqn里只有定义网络，没有单位数量相关的，main里的数量已经修改过了

**Comment by leonfg** [comment]
图像化obs的尺寸应该也有关系吧

**Comment by Jiang1206** [comment]
意思是网络输入的是运行的图像，所以改了地图大小后，网络输入大小也需要更改？那是整体的改还是只改输入？

**Comment by leonfg** [comment]
应该是只改输入就能跑 具体记不清了 太久远 自己研究下吧
