### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by CargoHu** [CETC-TFAI/MaCA#2]
Traceback (most recent call last):
  File "E:/code/github/MaCA/fight_mp.py", line 14, in <module>
    from interface import Environment
  File "E:\code\github\MaCA\environment\interface.py", line 15, in <module>
    from world.em_battle import BattleField
  File "E:\code\github\MaCA\environment\world\em_battle.py", line 1, in <module>
    __pyarmor__(__name__, __file__, b'...', 1)
  File "<frozen environment.world.em_battle>", line 27, in <module>
  File "E:\code\github\MaCA\environment\world\position_calc.py", line 1, in <module>
    __pyarmor__(__name__, __file__, '...', 1)
  File "<frozen environment.world.position_calc>", line 26, in <module>
ModuleNotFoundError: No module named 'numpy'

**Comment by leonfg** [comment]
> 
> 
> Traceback (most recent call last):
> File "E:/code/github/MaCA/fight_mp.py", line 14, in
> from interface import Environment
> File "E:\code\github\MaCA\environment\interface.py", line 15, in
> from world.em_battle import BattleField
> File "E:\code\github\MaCA\environment\world\em_battle.py", line 1, in
> **pyarmor**(**name**, **file**, b'...', 1)
> File "", line 27, in
> File "E:\code\github\MaCA\environment\world\position_calc.py", line 1, in
> **pyarmor**(**name**, **file**, '...', 1)
> File "", line 26, in
> ModuleNotFoundError: No module named 'numpy'

So please install additional package first.
```bash
pip install -U numpy pandas pygame
```
